name: Release CI

on:
  push:
    tags:
      - "trurl-*"

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    name: "ubuntu"

    steps:
    - uses: actions/checkout@v3

    - name: install libcurl
      run: |
        sudo apt-get update
        sudo apt-get install libcurl4-openssl-dev

    - name: make
      run: make test

    - name: sanity test
      run: ./trurl -v

    - name: test
      run: make ${{matrix.build.test}}

    - name: rename
      run: mv trurl trurl-ubuntu

    - name: artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Ubuntu
        path: ./trurl-ubuntu

  build-cygwin:
    runs-on: cygwin-latest
    name: "cygwin"

    steps:
      - uses: actions/checkout@v3

      - name: install cygwin
        uses: cygwin/cygwin-install-action@master
        with:
          packages: curl, libcurl-devel, libcurl4, make, gcc-core, python39

      - name: make
        run: make

      - name: sanity test
        run: ./trurl -v

      - name: test
        run: make test

      - name: rename
        run: mv trurl.EXE trurl-cygwin.exe

      - name: artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Cygwin
          path: ./trurl-cygwin.exe

  build-macos:
    runs-on: macos-latest
    name: "macos"

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: make
        run: make

      - name: sanity test
        run: ./trurl -v

      - name: test
        run: make test

      - name: rename
        run: mv trurl trurl-macos

      - name: artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Macos
          path: ./trurl-macos

  tagged-release:
    name: "Tagged Release"
    runs-on: ubuntu-latest
    permissions: write-all
    needs: [build-ubuntu, build-cygwin, build-macos]

    steps:
      - uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./Ubuntu/trurl-ubuntu
            ./Cygwin/trurl-cygwin.exe
            ./Macos/trurl-macos
